FROM redis:6.2.2
COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass Hqx2Oe18UAsVHqx2Oe18UAsVtEpQjuAzTXlWrrz0392a0uTmSvmdRtEpQjuAzTXlHqx2Oe18UAsVtEpQjuAzTXlWrrz0392a0uTmSvmdRWrrz0392a0uTmSvmdR"]